version: '3'

networks:
  link-net:
    driver: bridge

services:
  nginx:
    container_name: nginx
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: always
    ports:
      - 80:80
    networks:
      - link-net
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '1G'

  app:
    container_name: app
    build:
      context: ../app
      dockerfile: ../docker/next.Dockerfile
    volumes:
      - ../app/src:/app/src
      - ../app/public:/app/public
    restart: always
    networks:
      - link-net
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: '4G'

  api:
    container_name: api
    build:
      context: ../api
      dockerfile: ../docker/node.Dockerfile
    volumes:
      - ../api/dist/:/usr/src/api/dist/
    restart: always
    networks:
      - link-net
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: '4G'